# Docker Compose para desenvolvimento local
services:
  qrcode:
    image: tlgcode
    restart: always
    container_name: qrcode_website
    ports:
      - "8000:8000"
    volumes:
      - qr_user_volume:/app/static/user/
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID_QR:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET_QR:-}
      FLASK_ENV: development
      SERVER_NAME: localhost
      APPLICATION_ROOT: /qrcode
      PREFERRED_URL_SCHEME: http

networks:
  default:
    driver: bridge

volumes:
  qr_user_volume:
