services:
  qrcode:
    image: tlgcode
    restart: always
    container_name: qrcode_website
    volumes:
      - qr_user_volume:/app/static/user/
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID_QR:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET_QR:-}
      FLASK_ENV: ${FLASK_ENV:-production}
      SERVER_NAME: ${SERVER_NAME:-qrcode.guergolet.com.br}
      PREFERRED_URL_SCHEME: ${PREFERRED_URL_SCHEME:-https}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrcode.rule=Host(`qrcode.guergolet.com.br`) || Host(`qrcode.guergolet.art.br`) || Host(`qrcode.guergolet.sampa.br`)"
      - "traefik.http.routers.qrcode.entrypoints=web,websecure"
      - "traefik.http.routers.qrcode.tls=true"
      - "traefik.http.routers.qrcode.tls.certresolver=letsencrypt"
      - "traefik.http.routers.qrcode.priority=10"
      - "traefik.http.services.qrcode.loadbalancer.server.port=8000"
    networks:
      - devserver

networks:
  devserver:
    external: true

volumes:
  qr_user_volume: