version: '3.1'

services:
  qrcode:
    image: tlgcode
    restart: always
    container_name: qrcode_website
    volumes:
      - qr_user_volume:/app/static/user/
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID_QR}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET_QR}
      FLASK_ENV: production
      SERVER_NAME: www.guergolet.com.br
      APPLICATION_ROOT: /qrcode
      PREFERRED_URL_SCHEME: https
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrcode.rule=HostRegExp(`www\\.guergolet\\..+`) && PathPrefix(`/qrcode`)"
      - "traefik.http.routers.qrcode.entrypoints=web,websecure"
      - "traefik.http.routers.qrcode.tls=true"
      - "traefik.http.routers.qrcode.priority=0"
      - "traefik.http.services.qrcode.loadbalancer.server.port=5000"
      - "traefik.http.routers.qrcode.middlewares=redirect-to-https@file"
      - "traefik.http.routers.cdn.tls.certresolver=letsencrypt"
    networks:
      - devserver

networks:
  devserver:
    external: true
volumes:
  qr_user_volume:
