services:
  qrcode:
    image: tlgcode
    restart: always
    container_name: qrcode_website
    volumes:
      - qr_user_volume:/app/static/user/
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID_QR:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET_QR:-}
      FLASK_ENV: ${FLASK_ENV:-production}
      SERVER_NAME: ${SERVER_NAME:-guergolet.com.br}
      APPLICATION_ROOT: ${APPLICATION_ROOT:-/qrcode}
      PREFERRED_URL_SCHEME: ${PREFERRED_URL_SCHEME:-http}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrcode.rule=(Host(`guergolet.com.br`) || Host(`www.guergolet.com.br`) || Host(`www.guergolet.art`) || Host(`guergolet.art.br`) || Host(`guergolet.sampa.br`) ) && PathPrefix(`/qrcode`)"
      - "traefik.http.routers.qrcode.entrypoints=web,websecure"
      - "traefik.http.routers.qrcode.tls=true"
      - "traefik.http.routers.qrcode.tls.certresolver=letsencrypt"
      - "traefik.http.routers.qrcode.priority=10"
      - "traefik.http.services.qrcode.loadbalancer.server.port=8000"
    networks:
      - devserver

networks:
  devserver:
    external: true

volumes:
  qr_user_volume: