version: '3.1'

services:
  qrcode:
    image: tlgcode
    restart: always
    container_name: qrcode_website
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID_QR}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET_QR}
      FLASK_ENV: production
      SERVER_NAME: www.guergolet.com.br
      APPLICATION_ROOT: /qrcode
      PREFERRED_URL_SCHEME: https
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrcode.rule=Host(`guergolet.com.br`,`www.guergolet.com.br`, `guergolet.art`, `www.guergolet.art`, `guergolet.art.br`, `www.guergolet.art.br`, `guergolet.sampa.br`, `www.guergolet.sampa.br`) && PathPrefix(`/qrcode`)"
      - "traefik.http.routers.qrcode.entrypoints=web,websecure"
      - "traefik.http.routers.qrcode.tls=true"
      - "traefik.http.routers.qrcode.tls.certresolver=letsencrypt"
      - "traefik.http.routers.qrcode.priority=10"
      - "traefik.http.services.qrcode.loadbalancer.server.port=5000"
    networks:
      - devserver

networks:
  devserver:
    external: true
