version: '3.1'

services:
  qrcode:
    image: tlgcode
    restart: always
    container_name: qrcode_website
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID_QR}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET_QR}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrcode.rule=HostRegexp(`{subdomain:.*}guergolet.{domain:com\\.br|art|art\\.br|sampa\\.br}`) && PathPrefix(`/qrcode`)"
      - "traefik.http.routers.qrcode.entrypoints=web,websecure"
      - "traefik.http.routers.qrcode.tls=true"
      - "traefik.http.routers.qrcode.tls.certresolver=letsencrypt"
      - "traefik.http.services.qrcode.loadbalancer.server.port=5000"
    networks:
      - devserver

networks:
  devserver:
    external: true
